deploy_user: "infra"

wireguard_user: "wg_server"
wireguard_peers:
  - keenetic
  - iphone
  - macbook

wireguard_port: 51820
wireguard_config_dir: /opt/wireguard-server
wireguard_internal_subnet: 10.13.13.0
wireguard_dns:
  - 1.1.1.1
  - 1.0.0.1
wireguard_allowed_ips:
  - 0.0.0.0/0
  - ::/0
wireguard_local_dir: "./../wireguard_configs"

docker_users:
  - "{{ deploy_user }}"
  - "{{ wireguard_user }}"

security_ssh_allowed_users: 
  - "{{ deploy_user }}"
security_sudoers_passwordless:
  - "{{ deploy_user }}"
security_fail2ban_enabled: true
security_autoupdate_enabled: false

node_exporter_state: restarted
node_exporter_host: '127.0.0.1'
node_exporter_port: 9100

firewall_state: restarted
firewall_disable_firewalld: false
firewall_allowed_tcp_ports:
  - "22"
  - "{{ wireguard_port }}"
firewall_allowed_udp_ports: 
  - "{{ wireguard_port }}"
